In [1]:
import pandas as pd
import numpy as np
from math import sqrt

In [2]:
# Effective Field Goal percentage formula
#efg = FGM + (0.5 + 3PM) / FGA

In [3]:
shot_data_to_load = "Application Project/shots_data.csv"

In [4]:
shot_data_df = pd.read_csv(shot_data_to_load)
shot_data_df

team     x     y  fgmade
0    Team A  -5.0  26.4       0
1    Team A  -0.8   1.2       1
2    Team A -13.9   9.5       1
3    Team A  -5.4  26.2       0
4    Team A  -4.9  14.5       1
..      ...   ...   ...     ...
499  Team B  -0.5   2.2       0
500  Team B   3.5   7.6       0
501  Team B   0.2   8.8       0
502  Team B  -0.6   0.7       1
503  Team B  -0.3   3.6       0

[504 rows x 4 columns]

In [5]:
distance = {"d":[]}

In [6]:
for i,row in shot_data_df.iterrows():
    distance["d"].append(sqrt((row["x"])**2 + (row["y"])**2))

In [7]:
len(distance["d"])

504

In [8]:
shot_data_df["d"] = distance["d"]

In [9]:
#Seperating Team A and Team B
teamA_shots = shot_data_df[shot_data_df["team"] == "Team A"]
teamA_shots.head()

team     x     y  fgmade          d
0  Team A  -5.0  26.4       0  26.869313
1  Team A  -0.8   1.2       1   1.442221
2  Team A -13.9   9.5       1  16.836270
3  Team A  -5.4  26.2       0  26.750701
4  Team A  -4.9  14.5       1  15.305555

In [10]:
teamA_shots.count()

team      280
x         280
y         280
fgmade    280
d         280
dtype: int64

In [11]:
teamA_shots.dtypes

team       object
x         float64
y         float64
fgmade      int64
d         float64
dtype: object

In [12]:
teamA_shots

team     x     y  fgmade          d
0    Team A  -5.0  26.4       0  26.869313
1    Team A  -0.8   1.2       1   1.442221
2    Team A -13.9   9.5       1  16.836270
3    Team A  -5.4  26.2       0  26.750701
4    Team A  -4.9  14.5       1  15.305555
..      ...   ...   ...     ...        ...
275  Team A  -2.7  24.5       0  24.648327
276  Team A   4.2  10.3       1  11.123399
277  Team A  -9.0   1.2       1   9.079648
278  Team A   1.4  -0.1       0   1.403567
279  Team A   2.4   6.6       1   7.022820

[280 rows x 5 columns]

## Corner 3 shots for Team A

In [13]:
#Corner 3 index for Left Corner
idx1 = np.where((teamA_shots["x"] < -22.0) & (teamA_shots["y"] <= 7.8))
idx1

(array([ 36,  38,  99, 118, 134, 193, 196, 207, 221], dtype=int64),)

In [14]:
#Corner 3 index for Right Corner
idx2 = np.where((teamA_shots["x"] > 22.0) & (teamA_shots["y"] <=7.8))
idx2

(array([ 32, 122, 124, 125, 131, 137, 194, 200, 227], dtype=int64),)

In [15]:
# Left Corner
left_corner_A = teamA_shots.loc[idx1]
left_corner_A

team     x    y  fgmade          d
36   Team A -22.3 -0.8       1  22.314345
38   Team A -23.9  7.8       1  25.140605
99   Team A -22.9  4.5       1  23.337952
118  Team A -22.8  4.6       1  23.259407
134  Team A -22.9  0.6       1  22.907859
193  Team A -23.4 -1.1       0  23.425840
196  Team A -22.1  1.2       1  22.132555
207  Team A -23.0  0.8       1  23.013909
221  Team A -22.2  3.9       0  22.539965

In [16]:
left_corner_A.count()

team      9
x         9
y         9
fgmade    9
d         9
dtype: int64

In [17]:
# Right Corner
right_corner_A = teamA_shots.loc[idx2]
right_corner_A

team     x    y  fgmade          d
32   Team A  23.1 -1.2       0  23.131148
122  Team A  23.4  4.5       0  23.828764
124  Team A  23.1  2.3       0  23.214220
125  Team A  23.2  2.4       0  23.323808
131  Team A  22.4  5.5       1  23.065342
137  Team A  22.7  3.8       0  23.015864
194  Team A  23.8  0.8       1  23.813442
200  Team A  22.3  6.2       0  23.145842
227  Team A  22.8  0.0       0  22.800000

In [18]:
right_corner_A.count()

team      9
x         9
y         9
fgmade    9
d         9
dtype: int64

In [19]:
teamA_C3 = pd.concat([left_corner_A, right_corner_A])
teamA_C3

team     x    y  fgmade          d
36   Team A -22.3 -0.8       1  22.314345
38   Team A -23.9  7.8       1  25.140605
99   Team A -22.9  4.5       1  23.337952
118  Team A -22.8  4.6       1  23.259407
134  Team A -22.9  0.6       1  22.907859
193  Team A -23.4 -1.1       0  23.425840
196  Team A -22.1  1.2       1  22.132555
207  Team A -23.0  0.8       1  23.013909
221  Team A -22.2  3.9       0  22.539965
32   Team A  23.1 -1.2       0  23.131148
122  Team A  23.4  4.5       0  23.828764
124  Team A  23.1  2.3       0  23.214220
125  Team A  23.2  2.4       0  23.323808
131  Team A  22.4  5.5       1  23.065342
137  Team A  22.7  3.8       0  23.015864
194  Team A  23.8  0.8       1  23.813442
200  Team A  22.3  6.2       0  23.145842
227  Team A  22.8  0.0       0  22.800000

In [20]:
teamA_C3.count()

team      18
x         18
y         18
fgmade    18
d         18
dtype: int64

In [21]:
TeamA_total = teamA_shots["fgmade"].count()
TeamA_total

280

In [22]:
AC3_total = teamA_C3["fgmade"].count()
AC3_total

18

In [23]:
# Percentage of shots taken for Team A Corner 3
Corner_3_percentageA = AC3_total / float(TeamA_total) * 100
Corner_3_percentageA

6.428571428571428

In [24]:
a = (teamA_C3["fgmade"] == 1).sum()
a

9

In [25]:
# EFG for Corner 3 of Team A
efgAC3 = (a + (0.5 * a)) / AC3_total
efgAC3

0.75

## 2 Point shots for Team A

In [26]:
# 2 point shots
idx3 = np.where((teamA_shots["x"] >= -22.0) & (teamA_shots["x"] <= 22.0) & (teamA_shots["d"] <= 23.75))
idx3

(array([  1,   2,   4,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,
         19,  20,  22,  23,  24,  26,  27,  28,  29,  30,  31,  33,  37,
         39,  40,  41,  42,  43,  44,  47,  48,  49,  50,  51,  53,  54,
         57,  58,  59,  61,  62,  63,  64,  66,  67,  68,  69,  70,  71,
         72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  95,  96,  97,  98,
        100, 101, 102, 103, 107, 108, 109, 110, 112, 115, 119, 127, 129,
        130, 135, 136, 138, 139, 140, 141, 143, 144, 145, 148, 149, 150,
        153, 154, 155, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
        168, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 185, 186, 187, 188, 191, 201, 202, 203, 205, 209, 211, 212,
        213, 214, 215, 217, 218, 219, 220, 222, 225, 226, 228, 229, 230,
        231, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
        247, 248, 249, 251, 252, 253, 254, 255, 256

In [27]:
teamA_2 = teamA_shots.loc[idx3]
teamA_2

team     x     y  fgmade          d
1    Team A  -0.8   1.2       1   1.442221
2    Team A -13.9   9.5       1  16.836270
4    Team A  -4.9  14.5       1  15.305555
7    Team A  -7.3   5.7       0   9.261749
8    Team A  -2.8  11.0       1  11.350771
..      ...   ...   ...     ...        ...
273  Team A  -5.0   2.9       0   5.780138
276  Team A   4.2  10.3       1  11.123399
277  Team A  -9.0   1.2       1   9.079648
278  Team A   1.4  -0.1       0   1.403567
279  Team A   2.4   6.6       1   7.022820

[194 rows x 5 columns]

In [28]:
A2_total = teamA_2["fgmade"].count()
A2_total

194

In [29]:
# Percentage of shots taken for Team A 2 pointers
twopoint_percentageA = A2_total / float(TeamA_total) * 100
twopoint_percentageA

69.28571428571428

In [30]:
b = (teamA_2["fgmade"] == 1).sum()
b

95

In [31]:
# efg for 2 pointers
efgA2 = b / A2_total
efgA2

0.4896907216494845

## Non Corner 3 for Team A

In [32]:
# NC3 point shots
idx4 = np.where((teamA_shots["y"] > 7.8) & (teamA_shots["d"] > 23.75))
idx4

(array([  0,   3,   5,   6,  17,  18,  21,  25,  34,  35,  45,  46,  52,
         55,  56,  60,  65,  94, 104, 105, 106, 111, 113, 114, 116, 117,
        120, 121, 123, 126, 128, 132, 133, 142, 146, 147, 151, 152, 156,
        167, 169, 170, 184, 189, 190, 192, 195, 197, 198, 199, 204, 206,
        208, 210, 216, 223, 224, 232, 233, 234, 250, 258, 261, 263, 267,
        270, 274, 275], dtype=int64),)

In [33]:
teamA_NC3 = teamA_shots.loc[idx4]
teamA_NC3

team     x     y  fgmade          d
0    Team A  -5.0  26.4       0  26.869313
3    Team A  -5.4  26.2       0  26.750701
5    Team A -10.9  23.9       1  26.268232
6    Team A -12.0  23.6       1  26.475649
17   Team A  -8.2  24.8       0  26.120490
..      ...   ...   ...     ...        ...
263  Team A  -5.9  24.0       0  24.714571
267  Team A  15.2  19.9       1  25.040966
270  Team A  10.4  23.6       0  25.789921
274  Team A -10.9  24.5       1  26.815294
275  Team A  -2.7  24.5       0  24.648327

[68 rows x 5 columns]

In [34]:
ANC3_total = teamA_NC3["fgmade"].count()
ANC3_total

68

In [35]:
# Percentage for Non Corner 3 for Team A
NC3_A_percentage = ANC3_total / float(TeamA_total) * 100
NC3_A_percentage

24.285714285714285

In [36]:
c = (teamA_NC3["fgmade"] == 1).sum()
c

21

In [37]:
# efg for Non Corner 3 pointers
efgANC3 = (c + (0.5 * c)) / ANC3_total
efgANC3

0.4632352941176471

# Team B

In [38]:
#Seperating Team A and Team B
teamB_shots = shot_data_df[shot_data_df["team"] == "Team B"]
teamB_shots.head()

team     x     y  fgmade          d
280  Team B  -2.9  16.7       0  16.949926
281  Team B  10.3  24.7       0  26.761540
282  Team B  -3.5   5.3       1   6.351378
283  Team B   0.9   1.5       0   1.749286
284  Team B  22.8  -1.5       0  22.849289

In [39]:
teamB_shots = teamB_shots.reset_index()

In [40]:
del teamB_shots['index']

In [41]:
teamB_shots

team     x     y  fgmade          d
0    Team B  -2.9  16.7       0  16.949926
1    Team B  10.3  24.7       0  26.761540
2    Team B  -3.5   5.3       1   6.351378
3    Team B   0.9   1.5       0   1.749286
4    Team B  22.8  -1.5       0  22.849289
..      ...   ...   ...     ...        ...
219  Team B  -0.5   2.2       0   2.256103
220  Team B   3.5   7.6       0   8.367198
221  Team B   0.2   8.8       0   8.802272
222  Team B  -0.6   0.7       1   0.921954
223  Team B  -0.3   3.6       0   3.612478

[224 rows x 5 columns]

In [42]:
teamB_shots.count()

team      224
x         224
y         224
fgmade    224
d         224
dtype: int64

In [43]:
teamB_shots.dtypes

team       object
x         float64
y         float64
fgmade      int64
d         float64
dtype: object

## Team B Corner 3's

In [44]:
#Corner 3 index for Left Corner
idx5 = np.where((teamB_shots["x"] < -22.0) & (teamB_shots["y"] <= 7.8))
idx5

(array([ 41,  55, 123, 138], dtype=int64),)

In [45]:
#Corner 3 index for Right Corner
idx6 = np.where((teamB_shots["x"] > 22.0) & (teamB_shots["y"] <=7.8))
idx6

(array([  4,  33,  51,  56,  95, 124, 133], dtype=int64),)

In [46]:
# Left Corner
left_corner_B = teamB_shots.loc[idx5]
left_corner_B

team     x    y  fgmade          d
41   Team B -23.1  0.5       0  23.105411
55   Team B -22.3  0.4       0  22.303587
123  Team B -22.5  5.9       0  23.260696
138  Team B -23.1 -2.7       1  23.257257

In [47]:
left_corner_B.count()

team      4
x         4
y         4
fgmade    4
d         4
dtype: int64

In [48]:
# Right Corner
right_corner_B = teamB_shots.loc[idx6]
right_corner_B

team     x    y  fgmade          d
4    Team B  22.8 -1.5       0  22.849289
33   Team B  23.1  1.9       1  23.178007
51   Team B  23.4  6.6       0  24.312960
56   Team B  23.1  3.1       1  23.307080
95   Team B  23.3  2.4       0  23.423279
124  Team B  23.4 -1.2       0  23.430749
133  Team B  22.8  4.7       1  23.279390

In [49]:
right_corner_B.count()

team      7
x         7
y         7
fgmade    7
d         7
dtype: int64

In [50]:
teamB_C3 = pd.concat([left_corner_B, right_corner_B])
teamB_C3

team     x    y  fgmade          d
41   Team B -23.1  0.5       0  23.105411
55   Team B -22.3  0.4       0  22.303587
123  Team B -22.5  5.9       0  23.260696
138  Team B -23.1 -2.7       1  23.257257
4    Team B  22.8 -1.5       0  22.849289
33   Team B  23.1  1.9       1  23.178007
51   Team B  23.4  6.6       0  24.312960
56   Team B  23.1  3.1       1  23.307080
95   Team B  23.3  2.4       0  23.423279
124  Team B  23.4 -1.2       0  23.430749
133  Team B  22.8  4.7       1  23.279390

In [51]:
teamB_C3.count()

team      11
x         11
y         11
fgmade    11
d         11
dtype: int64

In [52]:
TeamB_total = teamB_shots["fgmade"].count()
TeamB_total

224

In [53]:
BC3_total = teamB_C3["fgmade"].count()
BC3_total

11

In [54]:
# Percentage of shots taken for Team B Corner 3
Corner_3_percentageB = BC3_total / float(TeamB_total) * 100
Corner_3_percentageB

4.910714285714286

In [55]:
d = (teamB_C3["fgmade"] == 1).sum()
d

4

In [56]:
# EFG for Corner 3 of Team B
efgBC3 = (d + (0.5 * d)) / BC3_total
efgBC3

0.5454545454545454

## 2 Point Shots for Team B

In [57]:
# 2 point shots
idx7 = np.where((teamB_shots["x"] >= -22.0) & (teamB_shots["x"] <= 22.0) & (teamB_shots["d"] <= 23.75))
idx7

(array([  0,   2,   3,   5,   6,   7,   8,  10,  13,  14,  15,  16,  17,
         18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  29,  31,  36,
         37,  38,  39,  40,  42,  43,  44,  50,  52,  53,  54,  57,  58,
         59,  60,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  79,  80,  81,  82,  83,  86,  87,  88,  89,  90,
         91,  94,  96,  97,  99, 100, 101, 102, 103, 104, 106, 107, 108,
        112, 113, 116, 117, 118, 120, 125, 126, 127, 131, 132, 134, 136,
        137, 139, 140, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 160, 163, 164, 165, 167, 169,
        170, 171, 173, 175, 177, 178, 179, 182, 183, 184, 185, 186, 187,
        188, 189, 190, 192, 193, 194, 195, 196, 200, 201, 202, 204, 205,
        208, 214, 215, 219, 220, 221, 222, 223], dtype=int64),)

In [58]:
teamB_2 = teamB_shots.loc[idx7]
teamB_2

team     x     y  fgmade          d
0    Team B  -2.9  16.7       0  16.949926
2    Team B  -3.5   5.3       1   6.351378
3    Team B   0.9   1.5       0   1.749286
5    Team B  13.3  11.8       0  17.780045
6    Team B -10.9  15.2       0  18.704278
..      ...   ...   ...     ...        ...
219  Team B  -0.5   2.2       0   2.256103
220  Team B   3.5   7.6       0   8.367198
221  Team B   0.2   8.8       0   8.802272
222  Team B  -0.6   0.7       1   0.921954
223  Team B  -0.3   3.6       0   3.612478

[151 rows x 5 columns]

In [59]:
B2_total = teamB_2["fgmade"].count()
B2_total

151

In [60]:
# Percentage of shots taken for Team B 2 pointers
twopoint_percentageB = B2_total / float(TeamB_total) * 100
twopoint_percentageB

67.41071428571429

In [61]:
e = (teamB_2["fgmade"] == 1).sum()
e

67

In [62]:
# efg for 2 pointers
efgB2 = e / B2_total
efgB2

0.44370860927152317

## Non Corner 3 for Team B

In [63]:
# NC3 point shots
idx8 = np.where((teamB_shots["y"] > 7.8) & (teamB_shots["d"] > 23.75))
idx8

(array([  1,   9,  11,  12,  28,  30,  32,  34,  35,  45,  46,  47,  48,
         49,  61,  76,  77,  78,  84,  85,  92,  93,  98, 105, 109, 110,
        111, 114, 115, 119, 121, 122, 128, 129, 130, 135, 141, 159, 161,
        162, 166, 168, 172, 174, 176, 180, 181, 191, 197, 198, 199, 203,
        206, 207, 209, 210, 211, 212, 213, 216, 217, 218], dtype=int64),)

In [64]:
teamB_NC3 = teamB_shots.loc[idx8]
teamB_NC3

team     x     y  fgmade          d
1    Team B  10.3  24.7       0  26.761540
9    Team B   8.5  28.7       0  29.932257
11   Team B -14.7  20.7       0  25.388580
12   Team B -10.4  24.6       0  26.708051
28   Team B   1.0  25.0       0  25.019992
..      ...   ...   ...     ...        ...
212  Team B  -8.9  23.9       0  25.503333
213  Team B   7.9  25.4       1  26.600188
216  Team B  15.6  23.7       0  28.373403
217  Team B -15.0  22.2       1  26.792536
218  Team B  -4.3  26.4       0  26.747897

[62 rows x 5 columns]

In [65]:
BNC3_total = teamB_NC3["fgmade"].count()
BNC3_total

62

In [66]:
# Percentage for Non Corner 3 for Team A
NC3_B_percentage = BNC3_total / float(TeamB_total) * 100
NC3_B_percentage

27.67857142857143

In [67]:
f = (teamB_NC3["fgmade"] == 1).sum()
f

21

In [68]:
# efg for Non Corner 3 pointers
efgBNC3 = (f + (0.5 * f)) / BNC3_total
efgBNC3

0.5080645161290323